FROM node:24 AS angular-build
WORKDIR /app
COPY TriviaApp.UI/package*.json ./TriviaApp.UI/
WORKDIR /app/TriviaApp.UI
RUN npm install
COPY ./TriviaApp.UI .
# RUN npm audit
RUN npm run build --omit=dev

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dotnet-build
WORKDIR /src
COPY ./TriviaApp.API .
RUN dotnet restore
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=angular-build /app/TriviaApp.UI/dist/TriviaApp.UI/browser/ /app/wwwroot
COPY --from=dotnet-build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "TriviaApp.API.dll"]
